name: sql_query_builder
description: SQL query builder for Postgres.
version: 1.0.0
repository: https://github.com/necessarylion/dart-sql-query-builder
homepage: https://github.com/necessarylion/dart-sql-query-builder

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  postgres: ^2.6.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
