name: dox_query_builder
description: PostgresSQL query builder, Support Model, Where, orWhere, Find, Join, softDeletes, Debugging and many mores.
version: 1.1.0
repository: https://github.com/necessarylion/dox-query-builder
homepage: https://github.com/necessarylion/dox-query-builder

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  postgres: ^2.6.1
  postgres_pool: ^2.1.6
  dox_annotation: ^0.0.2
  
dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  build_runner: ^2.3.3
  dox_builder: ^0.0.1
