name: Publish

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  Publish:
    permissions:
      id-token: write
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: postgres        
          POSTGRES_PASSWORD: password
          POSTGRES_USER: admin
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1

      - run: dart pub get
      - run: dart test --concurrency=1 
      - run: dart analyze
      - run: dart pub publish --force
